defaults: &defaults
  #app_name: "groupme"
  #domain: "http://groupme.dev"    
  facebook_app_id: 1441732272709306
  facebook_secret: "841a6ffcf19353d630ddff2a5c190595"
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: ""

development:
  <<: *defaults
  app_name: "groupme"
  domain: "http://groupme.dev"   


test:
  <<: *defaults

production:
  <<: *defaults
  app_name: "asiafxchange"
  domain: "http://dan-group-post.herokuapp.com/"  
